# Site settings
title: Kavish Blog
email: 
description: > # this means to ignore newlines until "baseurl:"
# Digital portal for my personal blogs and posts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kavishblog.appspot.com" # the base hostname & protocol for your site


collections:
  python:
    output: true
  others:
    output: true       


exclude:
  - bower_components
  - Gemfile
  

# Build settings
markdown: kramdown
kramdown:
  input: GFM  #Github Flavored Markdown

